# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4f793213c07aac03bd9866f7d0b20aef"
name = "Skailedâ„¢ Smart Links - KE"
application_url = "https://smartlinks-kissedearth.fly.dev"
embedded = true

[build]
automatically_update_urls_on_dev = false
dev_store_url = "kissedearth.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_product_listings,read_products,write_product_listings,write_products"

[auth]
redirect_urls = [
  "https://smartlinks-kissedearth.fly.dev/auth/callback",
  "https://smartlinks-kissedearth.fly.dev/auth/shopify/callback",
  "https://smartlinks-kissedearth.fly.dev/api/auth/callback"
]

[webhooks]
api_version = "2025-10"

[pos]
embedded = false
